apiVersion: v1
kind: Service
metadata:
  name: svc-petclinic
spec:
  selector:
    app: petclinic
    version: v1.0.0
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
# type 可以是 ClusterIP、NodePort、LoadBalancer

